# definitions:
#   image_defaults: &image_defaults
#     working_directory: ~/repo
#     docker:
#       - image: cypress/included:7.5.0
#         environment:
#           TERM: xterm

definitions:
  image_defaults: &image_defaults
    working_directory: ~/repo
    docker:
      - image: cypress/included:7.6.0
        environment:
          TERM: xterm

version: 2

orbs:
  percy: percy/agent

jobs:
#   checkout_install:
#     <<: *image_defaults
#     steps:
#       - checkout
#       - run: yarn global add @percy/agent lerna
#       - run: yarn
#       - run: npm rebuild node-sass
#       - run: yarn cypress:verify
#       - persist_to_workspace:
#           root: ~/
#           paths:
#             - .cache
#             - repo
#             - .yarn

  initialize:
    <<: *image_defaults
    steps:
      - checkout
      - run: yarn global add @percy/agent lerna
      - run: yarn
      - run: npm rebuild node-sass
      - run: yarn cypress:verify
      - run: yarn ci:build
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - repo
            - .yarn
            - dist
            - docs

  test-static:
    <<: *image_defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Test - Static
          command: yarn ci:test:lint

  test-source:
    <<: *image_defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Test - Source
          command: yarn ci:test:src

  test-examples:
    <<: *image_defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Test - Examples
          command: yarn ci:test:examples

  test-storybook:
    <<: *image_defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Test - Storybook
          command: yarn ci:test:storybook

#   lint:
#     <<: *image_defaults
#     steps:
#       - attach_workspace:
#           at: ~/
#       - run:
#           name: Lint all Libraries
#           command: yarn lint

#   build_tokens:
#     <<: *image_defaults
#     steps:
#       - attach_workspace:
#           at: ~/
#       - run:
#           name: Build tokens library
#           command: yarn build:tokens
#       - store_artifacts:
#           path: ~/repo/tokens/dist/
#       - persist_to_workspace:
#           root: ~/
#           paths:
#             - repo/tokens/dist/
#       - run:
#           name: Clear Git changed files
#           command: git checkout -- .


#   test_icons:
#     <<: *image_defaults
#     steps:
#       - attach_workspace:
#           at: ~/
#       - run:
#           name: Test icons library
#           command: yarn ci:test:icons
#       - run:
#           name: Clear Git changed files
#           command: git checkout -- .

#   test_core_percy:
#     <<: *image_defaults
#     steps:
#       - attach_workspace:
#           at: ~/
#       - run: yarn
#       - run:
#           name: Test core library with Percy.io snapshots
#           command: yarn ci:test:core:percy
#       - store_artifacts:
#           path: ~/repo/core/cypress/
#       - store_artifacts:
#           path: ~/repo/core/dist/
#       - run:
#           name: Clear Git changed files
#           command: git checkout -- .

#   test_react:
#     <<: *image_defaults
#     steps:
#       - attach_workspace:
#           at: ~/
#       - run: yarn
#       - run:
#           name: Unit Test react library
#           command: yarn test:CI
#       - run:
#           name: Test Storybooks with Percy
#           command: yarn examples:storybook:test
#       - run:
#           name: Visual regression test react library with Percy.io snapshots
#           command: yarn test:percy
#       - run:
#           name: Clear Git changed files
#           command: git checkout -- .

#   test_web_components:
#     <<: *image_defaults
#     steps:
#       - attach_workspace:
#           at: ~/
#       - run: yarn
#       - run:
#           name: Build web components library
#           command: yarn build:wc
#       - run:
#           name: Unit Test web components library
#           command: yarn ci:test:wc
#       - run:
#           name: Build Storybook
#           command: yarn storybook:wc-dist
#       - run:
#           name: Clear Git changed files
#           command: git checkout -- .

#   storybook_web_components:
#     <<: *image_defaults
#     steps:
#       - attach_workspace:
#           at: ~/
#       - run: yarn
#       - run:
#           name: Build web components library
#           command: yarn build:wc
#       - run:
#           name: Deploy Storybook
#           command: yarn storybook:wc-deploy
#       - run:
#           name: Clear Git changed files
#           command: git checkout -- .

#   static_analysis:
#     <<: *image_defaults
#     steps:
#       - attach_workspace:
#           at: ~/
#       - run: yarn
#       - run:
#           name: Build web components library
#           command: yarn build:wc
#       - run:
#           name: Unit Test web components library
#           command: yarn ci:test:wc
#       - run: 
#           name: Upload Codecov report
#           command: bash <(curl -s https://codecov.io/bash)
#       - run:
#           name: Clear Git changed files
#           command: git checkout -- .

#   percy_finalize_all:
#     working_directory: ~/repo
#     docker:
#       - image: percyio/agent:latest
#     steps:
#       - attach_workspace:
#           at: ~/
#       - run: PERCY_TOKEN=$PERCY_TOKEN percy finalize --all

#   test_www:
#     <<: *image_defaults
#     steps:
#       - attach_workspace:
#           at: ~/
#       - run: yarn
#       - run:
#           name: Integration testing for www with Cypress.io
#           command: yarn ci:test:www
#       - run:
#           name: Clear Git changed files
#           command: git checkout -- .

#   lint_test_release:
#     <<: *image_defaults
#     steps:
#       - checkout
#       - run:
#           name: Install Dependencies
#           command: yarn global add @percy/agent lerna && yarn install --frozen-lockfile --non-interactive
#       - run: yarn
#       - run: npm rebuild node-sass
#       - run: yarn cypress:verify
#       - run:
#           name: Lint all Libraries
#           command: yarn lint:all
#       - run: yarn build:react
#       - run:
#           name: Build tokens library
#           command: yarn build:tokens
#       - run:
#           name: Test icons library
#           command: yarn ci:test:icons
#       - run:
#           name: Test core library
#           command: yarn ci:test:core
#       - run:
#           name: Test react library
#           command: yarn ci:test:react
#       - run:
#           name: Clear Git changed files
#           command: git checkout -- .
#       - add_ssh_keys:
#           fingerprints:
#             - "8d:03:46:48:16:a2:7f:d4:97:2f:20:a1:fe:0e:81:35"
#       - run:
#           name: Configure git defaults
#           command: git config user.email $GH_EMAIL && git config user.name $GH_USER
#       - run: echo "registry=https://registry.npmjs.org" > ~/.npmrc
#       - run: echo "registry \"https://registry.npmjs.org\"" > ~/.yarnrc
#       - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
#       - run: git status
#       - run:
#           name: Publish Releases
#           command: yarn release
#       - run:
#           name: Update examples
#           command: yarn data
#       - run:
#           name: Integration testing for www with Cypress.io
#           command: yarn ci:test:www
#       - run:
#           name: Publish website
#           command: yarn publish:www

#   publish_www:
#     <<: *image_defaults
#     steps:
#       - checkout
#       - run:
#           name: Install Dependencies
#           command: yarn global add @percy/agent lerna && yarn install --frozen-lockfile --non-interactive
#       - run: yarn
#       - run: npm rebuild node-sass
#       - run:
#           name: Build website
#           command: yarn build:www
#       - run:
#           name: Publish website
#           command: yarn publish:www

workflows:
  version: 2
  pull-request:
    jobs:
      - initialize
      - test-static:
          requires:
            - initialize
      - test-source:
          requires:
            - initialize
      # - test-examples:
      #     requires:
      #       - test-static
      #       - test-source
      - test-storybook:
          requires:
            - test-static
            - test-source
      - percy/finalize_all:
          requires:
            # - test-examples
            - test-storybook
            
#   lint_test:
#     jobs:
#       - checkout_install
#       - lint:
#           requires:
#             - checkout_install
#       - test_react:
#           requires:
#             - checkout_install
#       - percy_finalize_all:
#           requires:
#             - test_react
